# Generated by Django 4.2.1 on 2023-06-05 14:19

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="Place_info",
            fields=[
                ("contentsid", models.TextField()),
                ("kakaoid", models.TextField(primary_key=True, serialize=False)),
                ("category", models.TextField()),
                ("title", models.TextField()),
                ("alltag", models.TextField(blank=True, default="")),
                ("tag", models.TextField()),
                ("address", models.TextField()),
                ("latitude", models.TextField()),
                ("longitude", models.TextField()),
                ("thumbnail", models.TextField()),
                ("star", models.TextField()),
                ("starnum", models.TextField()),
            ],
        ),
        migrations.CreateModel(
            name="Place_keywords",
            fields=[
                ("contentsid", models.TextField()),
                ("kakaoid", models.TextField(primary_key=True, serialize=False)),
                ("category", models.TextField()),
                ("experience", models.IntegerField()),
                ("activity", models.IntegerField()),
                ("nature", models.IntegerField()),
                ("beach", models.IntegerField()),
                ("rest", models.IntegerField()),
                ("photo", models.IntegerField()),
                ("parents", models.IntegerField()),
                ("children", models.IntegerField()),
                ("couples", models.IntegerField()),
                ("friends", models.IntegerField()),
            ],
        ),
    ]
