# Generated by Django 4.2.1 on 2023-06-01 22:02

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="Place_info",
            fields=[
                ("contentsid", models.TextField()),
                ("kakaoid", models.TextField(primary_key=True, serialize=False)),
                ("category", models.TextField()),
                ("title", models.TextField()),
                ("alltag", models.TextField(blank=True, default="")),
                ("tag", models.TextField()),
                ("address", models.TextField()),
                ("latitude", models.TextField()),
                ("longitude", models.TextField()),
                ("thumbnail", models.TextField()),
                ("star", models.TextField()),
                ("starnum", models.TextField()),
            ],
        ),
        migrations.CreateModel(
            name="Place_keywords",
            fields=[
                ("contentsid", models.TextField()),
                ("kakaoid", models.TextField(primary_key=True, serialize=False)),
                ("category", models.TextField()),
                ("experience", models.IntegerField()),
                ("activity", models.IntegerField()),
                ("nature", models.IntegerField()),
                ("beach", models.IntegerField()),
                ("rest", models.IntegerField()),
                ("photo", models.IntegerField()),
                ("parents", models.IntegerField()),
                ("children", models.IntegerField()),
                ("couples", models.IntegerField()),
                ("friends", models.IntegerField()),
            ],
        ),
        migrations.CreateModel(
            name="Plan",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("planid", models.IntegerField()),
                ("startdate", models.DateField()),
                ("enddate", models.DateField()),
                ("starttime", models.IntegerField()),
                ("endtime", models.IntegerField()),
            ],
        ),
        migrations.CreateModel(
            name="Plan_detail",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("planid", models.IntegerField()),
                ("seq", models.IntegerField()),
                ("kakaoid", models.TextField()),
            ],
        ),
    ]
