# Generated by Django 4.2.1 on 2023-06-05 14:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("api", "0001_initial"),
    ]

    operations = [
        migrations.CreateModel(
            name="Plan",
            fields=[
                ("Planid", models.IntegerField(primary_key=True, serialize=False)),
                ("Plandata", models.TextField()),
            ],
        ),
    ]
