# Generated by Django 4.2.1 on 2023-06-01 22:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("api", "0002_delete_plan"),
    ]

    operations = [
        migrations.CreateModel(
            name="Plan",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("planid", models.IntegerField()),
                ("startdate", models.DateField()),
                ("enddate", models.DateField()),
                ("starttime", models.IntegerField()),
                ("endtime", models.IntegerField()),
            ],
        ),
    ]
